default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      user: dbt_mateusz
      password: ${{ secrets.SNOWFLAKE_DBT_PASSWORD }}

      database: SEGMENT_EVENTS
      warehouse: SEGMENT_WH

      schema: DBT
      threads: 4