default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }}
      user: dbt_mateusz
      password: {{ env_var('SNOWFLAKE_DBT_PASSWORD') }}

      database: SEGMENT_EVENTS
      warehouse: SEGMENT_WH

      schema: DBT
      threads: 4