name: analysis

on:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Install re_data and python dependencies
        working-directory: .
        run: |
          pip install dbt-snowflake
          pip install re_data
          pip install re_cloud
          
      - name: Run dbt
        working-directory: .
        run: |
          dbt --version
          dbt deps
          dbt run --select package:analysis