name: analysis

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}
  RE_DATA_CONFIG_DIR: ${{ github.workspace }}
  RE_DATA_SEND_ANONYMOUS_USAGE_STATS: 0
  RE_CLOUD_API_KEY: ${{ secrets.RE_CLOUD_API_KEY }}
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_DBT_PASSWORD: ${{ secrets.SNOWFLAKE_DBT_PASSWORD }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Install re_data and python dependencies
        working-directory: .
        run: |
          pip install dbt-snowflake
          pip install re_data
          pip install re_cloud

      - name: Run dbt
        working-directory: .
        run: |
          dbt --version
          dbt deps
          dbt run --select package:analysis

      - name: Configure re_data.yml
        uses: mikefarah/yq@master
        with:
          working-directory: .
          cmd: |
            yq -i '.re_cloud.api_key = "${{secrets.RE_CLOUD_API_KEY}}"' re_data.yml 
      
      - name: Compute and upload dbt docs
        working-directory: .
        run: |
          dbt docs generate
          re_cloud upload dbt-docs --name analytics-docs 

      - name: Compute and upload re_data report
        working-directory: .
        run: |
          re_data run
          re_cloud upload dbt-docs --name analytics-docs 
          re_cloud upload re_data --name analytics-report
